config:
  clientId: ''
  apiKey: ''
  projectName: 'SOOS DAST Analysis'
  scanMode: 'baseline'
  failOnError: 'continue_on_error'
  rules: ''
  context:
    file: ''
    user: ''
  apiURL: 'https://app.soos.io/api/'
  debug: false
  ajaxSpider: false
  fullScan:
    minutes: ''
  apiScan:
    format: 'openapi'
  activeScan:

